=== chuckcranor/emulab-devel/assign/ptop.dtd
<!ELEMENT ptop (node*,link*)>
<!ATTLIST ptop testbed CDATA #REQUIRED>

<!-- Nodes -->

<!ELEMENT node (node_type+,node_feature*,node_option*)>
<!ATTLIST node name ID #REQUIRED>

<!ELEMENT node_type (type_name,(limit|unlimited))>
<!ATTLIST node_type is_static (yes | no) "no">
<!-- Include something about 'switch' or 'transit' -->

<!ELEMENT type_name EMPTY>
<!ATTLIST type_name name CDATA #REQUIRED>

<!ELEMENT limit EMPTY>
<!ATTLIST limit slots CDATA #REQUIRED>

<!ELEMENT unlimited EMPTY>

<!ELEMENT node_feature (feature_name,feature_weight)>
<!ATTLIST node_feature type (normal | local-additive | global-exclusive |
                             global-inclusitve) "normal"
                       violatable (yes | no) "no">
<!ELEMENT feature_name EMPTY>
<!ATTLIST feature_name name CDATA #REQUIRED>
<!ELEMENT feature_weight EMPTY>
<!ATTLIST feature_weight weight CDATA #REQUIRED>

<!ELEMENT node_option (option_name,option_value)>
<!-- Stronger 'typing'? -->
<!ELEMENT option_name EMPTY>
<!ATTLIST option_name name CDATA #REQUIRED>
<!ELEMENT option_value EMPTY>
<!ATTLIST option_value value CDATA #REQUIRED>

<!--- Links -->

<!ELEMENT link (endpoint,endpoint,delay_spec,link_type+)>
<!ATTLIST link name ID #REQUIRED>

<!ELEMENT endpoint EMPTY>
<!ATTLIST endpoint node IDREF #REQUIRED
                   interface CDATA #REQUIRED>
<!ELEMENT delay_spec (bandwidth,delay,loss)>
<!ELEMENT bandwidth EMPTY>
<!ATTLIST bandwidth value CDATA #REQUIRED>
<!ELEMENT delay EMPTY>
<!ATTLIST delay value CDATA #REQUIRED>
<!ELEMENT loss EMPTY>
<!ATTLIST loss value CDATA #REQUIRED>
<!ELEMENT link_type EMPTY>
<!ATTLIST link_type type CDATA #REQUIRED>

=== chuckcranor/emulab-devel/assign/test-ptop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ptop SYSTEM "ptop.dtd">
<ptop testbed="emulab">
    <node name="pc1">
        <node_type>
            <type_name name="pc650" />
            <limit slots="1" />
        </node_type>
        <node_type>
            <type_name name="delay" />
            <limit slots="2" />
        </node_type>
        <node_type is_static="yes">
            <type_name name="delayinfo" />
            <limit slots="2" />
        </node_type>
        <node_feature>
            <feature_name name="feature1" />
            <feature_weight weight="1.0" />
        </node_feature>
        <node_feature type="local-additive" violatable="yes">
            <feature_name name="feature2" />
            <feature_weight weight="0.5" />
        </node_feature>
        <node_option>
            <option_name name="trivial_bw" />
            <option_value value="400" />
        </node_option>
    </node>
    <node name="pc2">
        <node_type>
            <type_name name="pc650" />
            <limit slots="1" />
        </node_type>
        <node_type>
            <type_name name="delay" />
            <limit slots="2" />
        </node_type>
        <node_type is_static="yes">
            <type_name name="delayinfo" />
            <limit slots="2" />
        </node_type>
        <node_feature>
            <feature_name name="feature1" />
            <feature_weight weight="1.0" />
        </node_feature>
        <node_feature type="local-additive" violatable="yes">
            <feature_name name="feature2" />
            <feature_weight weight="0.5" />
        </node_feature>
        <node_option>
            <option_name name="trivial_bw" />
            <option_value value="400" />
        </node_option>
    </node>
    <link name="link1">
        <endpoint node="pc1" interface="eth0" />
        <endpoint node="pc2" interface="eth0" />
        <delay_spec>
            <bandwidth value="100Mbps" />
            <delay value="0ms" />
            <loss value="0.00" />
        </delay_spec>
        <link_type type="ethernet" />
    </link>
</ptop>
